Bugfix/affinity trust fixes and watch functions
Just-Natsuki-Team/NatsukiModDev pull request #102
Opened 2021-11-04 20:20 UTC by Blizzardsev

This will introduce the following:
- New debug utilities allowing easy use of the `renpy.watch()`/`renpy.unwatch() `functionalities; can add/remove statements to a list of watched items that can be easily brought up via topic ingame instead of having to go via console every time.
- Fixed a bug where the `talk_flavor_text` when menuing wasn't consistent with the player's current affinity.
- Fixed a bug where `get_affinity_state()`/`trust_state()` functionality would not return the correct affinity/trust state when below the minimum thresholds, and would return `None`.
- Adjustments to `jn_affinity` to bring trust handling in line with affinity handling.

Closes #101

2021-11-07 01:11 UTC, JustNatsFang requested changes

2021-11-07 01:11 UTC, JustNatsFang commented on game/script-topics.rpy
> +    return
We should add dev stuff to a folder for them and their own files, so they won't end up in production builds

2021-11-07 01:11 UTC, JustNatsFang commented on game/script-topics.rpy
>              unlocked=True,
We should move this too

2021-11-09 00:54 UTC, Blizzardsev commented
No longer required - will be overtaken by test/blizzardsev merge.

2021-11-09 00:54 UTC, closed without merging