[FEATURE] copypasting for Renpy's Input
Just-Natsuki-Team/NatsukiModDev pull request #127
Opened 2021-12-22 10:01 UTC by spaghetsie

This introduces the following
- `Ctrl+C` copy
- `Ctrl+V` paste
- `Ctrl+X` cut
- `Ctrl+A` select all
- `Ctrl+Home` select from caret to beginning of text
- `Ctrl+End` select from caret to end of text
- `Ctrl+left` move selection left
- `Ctrl+right` move selection right

  this follows Input's allowed and excluded characters, as well as max length

2021-12-22 13:10 UTC, Blizzardsev approved these changes

2021-12-22 15:47 UTC, multimokia requested changes
Some things

2021-12-22 15:47 UTC, multimokia commented on game/input_additions.rpy
> +init 999 python in Input_overwrite:
Small consistency thing. Also we should going forward prefix our vars/classes/funcions/etc. with a prefix to indicate it's global. (Kinda like a prod name before the package)
```suggestion
init 999 python in jn_input_overwrite:
```

2021-12-22 15:47 UTC, multimokia commented on game/input_additions.rpy
> +    map_event = renpy.display.behavior.map_event
Can you add a comment indicating what this does here? Coming at a glance, would make sense to re-add a little bit of docs to help people understand what the function does

2021-12-23 17:17 UTC, Blizzardsev approved these changes

2021-12-23 17:17 UTC, multimokia approved these changes

2021-12-23 17:38 UTC, merged