added chocolate_plaid_collection
Just-Natsuki-Team/NatsukiModDev pull request #567
Opened 2023-03-03 19:40 UTC by RaionArt

Chocolate_plaid_collection consists of:
-`chocolate_plaid_bow`
-`chocolate_plaid_dress`
-`golden_necklace`

Also added the topic `chocolate_preference` to have the outfit unlockable on higher affinity.

2023-03-06 18:40 UTC, Blizzardsev commented on game/script-topics.rpy
> +        and persistent.jn_custom_outfits_unlocked
Good use of conditioning here - well done!

2023-03-06 19:11 UTC, Blizzardsev requested changes
Just added some thoughts!

I think the wording could use adjustment, but the ideas behind it are solid - I like the idea of Natsuki spelling out the link between the clothes and the topic; it helps solidify why it's being unlocked specifically and feels natural!

Good work on the code side of things: you know what you're doing with the registration code, and I'm happy to see how you managed the implementation/switch in the dialogue itself: well done! We might want to consider the event that a user has already read the topic and if it should be unlocked automatically for those that have, but that's just a thought.

2023-03-06 19:11 UTC, Blizzardsev commented on game/script-topics.rpy
> +        extend 3fchcs " Ehehe."
I should note: I've left the sprite codes empty so you can try giving those lines a shot if you agree with the suggestions!

2023-03-06 19:57 UTC, RaionArt commented on game/script-topics.rpy
> +        n 4fcssresp "..."
Ah! Tbh I wanted to do it this way, but I wasn't sure if it works without an else, this is fine by me

2023-03-08 18:45 UTC, Blizzardsev approved these changes

2023-03-09 17:55 UTC, merged