Gaming topic
Just-Natsuki-Team/NatsukiModDev pull request #64
Opened 2021-10-01 17:26 UTC by Blizzardsev

This will introduce the following:

- One new topic, `talk_gaming`.

Closes #63

2021-10-01 17:55 UTC, JustNatsFang requested changes

2021-10-01 17:55 UTC, JustNatsFang commented on game/script-topics.rpy
> +            conditional=None,
Don't think we need to specify `conditional=None` as this should be the default value already if I'm correct.

2021-10-01 17:55 UTC, JustNatsFang commented on game/script-topics.rpy
> +            $ gaming_choice = 0
Ideally it might make sense to add a persistent variable for this, we can probably use this for other dialogue branching here and there.

2021-10-01 18:36 UTC, JustNatsFang submitted a review, later dismissed

2021-10-20 13:55 UTC, Trainerbluetube commented on game/script-topics.rpy
> +            n "Relax,{w=0.1} [player]!"
Line 1861: Could add "I'm just messing with you!" after the existing dialogue on this line.

2021-10-20 13:57 UTC, Trainerbluetube submitted a review, later dismissed
I think the topic is good as-is, we could reboot it later to add more player interaction (aka types of games players enjoy, getting Natsuki's opinion on those) but it's good as-is.

2021-11-09 00:54 UTC, Blizzardsev commented
No longer required - will be overtaken by test/blizzardsev merge.

2021-11-09 00:54 UTC, closed without merging