Get the game running in Ren'Py 7.6
Just-Natsuki-Team/NatsukiModDev pull request #716
Opened 2023-05-23 03:12 UTC by einstein95

Also adding more stuff to .gitignore so that game stuff doesn't get flagged by git.

Only thing now is to fix the recursion error when renpy.quit() is called

2023-05-23 07:45 UTC, einstein95 commented
@Blizzardsev that's fair. The recursion error seems to be caused by zz_config.rpy setting `config.quit_action` to be `quit_input_check`, and then that function jumping to `quit` which then calls `renpy.quit()` which calls that function...

2023-05-23 08:10 UTC, Blizzardsev commented
Seeing as how that's current functionality, then my guess would be a change in the behaviour of `renpy.quit()` between versions: a good place to start would be going through the changelogs for Ren'Py post-7 and seeing where/if the behaviour of that function is modified, and how.

If `renpy.quit()` now has a hard link to `config.quit_action` instead of just quitting the game, then we'd need to either see if the changes add a parameter we can use to stop that, use a replacement function or try dummying out `config.quit_action` just before we call it.

2023-05-23 08:36 UTC, einstein95 commented
I was incorrect in debugging the error, it was caused by the label being called `quit`, which `renpy.quit()` jumps to if it's defined (introduced by https://github.com/renpy/renpy/commit/e281635b471e34c9f6a62566877c56bd9e024c5d). I've renamed the label to `save_quit` (as it saves, then quits) and it fixes the error.

The TODO introduced in this PR does not seem to affect the game, as it seems to only affect the transition when bringing up the menu of topics to talk about. Further regression testing may be needed.

2023-05-23 08:57 UTC, Blizzardsev commented
Good stuff - always nice for the solution to be quick and easy, well done.

See if you can get a handle on that transition if you can: the categorized menu is pretty front and centre visually being used for the main game menu, so we would want to preserve that behaviour if possible: might be as providing the `at` statement at the point of showing the screen.

2023-05-24 06:22 UTC, einstein95 commented
After comparing the behavior in 7.6 and the current RenPy 6 version, it doesn't change anything. From what I can see, it was added in at some point so that the list of topics would slide in from the right, however I think this functionality broke at some point without people noticing or never worked.

2023-05-25 17:40 UTC, Blizzardsev requested changes
Minor changes. My main concern here is going to be the amount of changes to packages as a result of the move: particularly those related to making requests.

Have you tested the weather-related setup to ensure that still works as expected?

2023-05-25 17:40 UTC, Blizzardsev commented on game/screens.rpy
> +    # at categorized_menu_slide_in_right
Can we remove this please?

2023-05-28 11:10 UTC, einstein95 commented on game/screens.rpy
> +    # at categorized_menu_slide_in_right
Done

2023-05-28 11:15 UTC, einstein95 commented
> Minor changes. My main concern here is going to be the amount of changes to packages as a result of the move: particularly those related to making requests.
> 
> Have you tested the weather-related setup to ensure that still works as expected?

Yes, I've had the weather change perfectly fine.

Since Renpy 7 is still python 7, the packages haven't needed updating, I've only done so for these packages so that they'll still continue to work for the near future and to smooth over any further update to Renpy 8, as Renpy 7 will only be supported for a year.

2023-05-29 12:54 UTC, Blizzardsev approved these changes

2023-05-29 12:55 UTC, Blizzardsev commented
Cool. I'd like to run through the engine change in more detail personally, but until then I'll merge it in.

2023-05-29 12:56 UTC, merged