Feature/potted plant intro
Just-Natsuki-Team/NatsukiModDev pull request #754
Opened 2023-06-24 18:01 UTC by Blizzardsev

Introduces the following:

- New event `event_sanjo`; introducing a new, somewhat spiky companion for Natsuki in the classroom
- Two new greetings:
    - `greeting_sanjo_morning`
    - `greeting_sanjo_generic`
- Desk items no longer store disps, and take an image path (disp created as needed when setting the item) instead to reduce memory usage
- Improved handling for desk items; supplying a `JNDeskItem` as the item parameter when calling `setDeskItem` no longer requires a slot (as this is specified on the item anyway)
- Improve `script-ch30` load sequence for greetings; greetings can now specify a desk item and expression for Natsuki to be set before the black screen fades out
- Various small adjustments/corrections

2023-06-24 21:05 UTC, RaionArt requested changes
The event is fun and it's nice to see Natsuki so involved and motivated!  I only noticed some small stuff that might need adjustment. 
Also didn't we plan to add a line or two to the pets topic, after the player experienced the plotted plant intro? 
Either way good job so far! I also appreciate the new facial expression while she waits for a response and like always it's nice to notice how she gets less defensive at higher affinity.

2023-06-25 18:55 UTC, Blizzardsev commented on game/script-events.rpy
> +            n 3fcsgs "You trying to say it needs an {i}excuse{/i} to be here or something?{w=0.75}{nw}"
Good catch; I missed this one

2023-06-25 18:55 UTC, Blizzardsev commented on game/script-events.rpy
> +        "Looks like you and that plant both have something in common.":
Sure, I can look at rephrasing this

2023-06-25 18:56 UTC, Blizzardsev commented on game/script-events.rpy
> +    n "...And what kind of inconsiderate jerk just left you {i}there{/i}?"
Sure, I can add a little bit for this

2023-06-25 20:02 UTC, RaionArt approved these changes
Thank you for the adjustments! 
I love to have another wholesome intro event under out belt. Great job!

2023-06-25 20:03 UTC, merged